import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {generateKeyPairSync,sign,randomUUID} from 'node:crypto';
import {startLocal} from './local.mjs';
import {makePlan,importOfficial,hash} from './official.mjs';
import {backupRegistry,restoreRegistry} from './backup.mjs';
import {remoteBindings} from './official-remote.mjs';
const root=path.resolve('../..'),out=path.resolve(process.env.OFFICIAL_OUTPUT||root+'/.qa/official/operator');fs.mkdirSync(out,{recursive:true});
const lab=fs.mkdtempSync(path.join(os.tmpdir(),'cg-official-')),checks=[],commands=[],services=[];
const artifact=path.join(root,'dist/extensions/drupal.cgext'),bytes=fs.readFileSync(artifact);
const keys=generateKeyPairSync('ec',{namedCurve:'prime256v1'});
const servicesStart=async name=>{const state=path.join(lab,name),s=await startLocal({state});services.push(s);s.state=state;s.target={mode:'local',state,registryId:await s.db.prepare("SELECT value FROM registry_meta WHERE key='id'").first('value'),engineVersion:'1.6.0'};return s;};
function pass(name){checks.push(name);fs.writeFileSync(path.join(out,'progress.json'),JSON.stringify({checks,commands},null,2));console.log('PASS',name);}
function signed(artifact,extra={}){const payload=JSON.stringify({name:'Community',description:'Test',publisher:'Community',readme:'Test',source:'https://example.com/source',artifact:artifact.toString('base64'),timestamp:Date.now(),nonce:randomUUID(),...extra});return {payload,publicKey:keys.publicKey.export({format:'jwk'}),signature:sign('sha256',Buffer.from(payload),{key:keys.privateKey,dsaEncoding:'ieee-p1363'}).toString('base64')};}
async function submit(s,body,status){const r=await fetch('http://127.0.0.1:'+s.port+'/api/publish',{method:'POST',body:JSON.stringify(body)});assert.equal(r.status,status,await r.clone().text());return r.json();}
async function cli(args,exit=0){const r=await new Promise((resolve,reject)=>{const c=spawn(process.execPath,['official-cli.mjs',...args],{timeout:30000});let stdout='',stderr='';c.stdout.on('data',b=>stdout+=b);c.stderr.on('data',b=>stderr+=b);c.on('error',reject);c.on('close',code=>resolve({exit:code,stdout,stderr}));});const log='command-'+(commands.length+1)+'.log';fs.writeFileSync(path.join(out,log),r.stdout+r.stderr);commands.push({command:[process.execPath,'official-cli.mjs',...args],exit:r.exit,sha256:hash(r.stdout+r.stderr),log});assert.equal(r.exit,exit,r.stderr);return r.stdout;}
try{
 const s=await servicesStart('main'),plan=makePlan(bytes,s.target,artifact);
 const unsupported=JSON.parse(bytes);unsupported.package.codegraph.apiVersion=9;assert.throws(()=>makePlan(Buffer.from(JSON.stringify(unsupported)),s.target,artifact),/unsupported API/);pass('unsupported extension API rejected before writes');
 assert.throws(()=>makePlan(Buffer.from('{}'),s.target,artifact),/Invalid/);pass('malformed package rejected before writes');
 assert.throws(()=>makePlan(bytes,{...s.target,engineVersion:'9.0.0'},artifact),/requires CodeGraph/);pass('incompatible target engine rejected before writes');
 assert.throws(()=>makePlan(Buffer.concat([bytes,Buffer.from(' ')]),s.target,artifact),/integrity/);pass('tampered but valid JSON package rejected by reviewed provenance pin');
 await assert.rejects(()=>importOfficial(s.db,s.bucket,{...plan,listing:{...plan.listing,name:'forged'}},bytes),/plan changed/);pass('edited publication plan rejected');
 const wrong=makePlan(bytes,{...s.target,registryId:'0'.repeat(32)},artifact);await assert.rejects(()=>importOfficial(s.db,s.bucket,wrong,bytes),/identity/);pass('wrong registry identity rejected');
 const result=await importOfficial(s.db,s.bucket,plan,bytes);assert.equal(result.status,'imported');assert.equal(result.listing.publisherId,'codegraph');assert.equal(result.listing.official,true);assert.deepEqual(Buffer.from(await(await s.bucket.get('packages/sha256/'+plan.listing.integrity)).arrayBuffer()),bytes);pass('official identity provenance and exact bytes published through real D1/R2');
 assert.equal((await importOfficial(s.db,s.bucket,makePlan(bytes,s.target,artifact),bytes)).status,'unchanged');pass('safe repeated plan is idempotent and retains original listing');
 const other=JSON.parse(bytes);other.package.codegraph.id='unofficial';other.package.name='unofficial';const community=Buffer.from(JSON.stringify(other));
 for(const extra of [{official:true},{publisherId:'codegraph'},{provenance:{revision:'fake'}}])await submit(s,signed(community,extra),400);
 const normal=await submit(s,signed(community),201);assert.equal(normal.official,false);assert.notEqual(normal.publisherId,'codegraph');pass('public API rejects official identity spoof while preserving community publication');
 await submit(s,signed(bytes),400);pass('community cannot replace reserved official Drupal ownership');
 const owner=await servicesStart('owner-conflict');await submit(owner,signed(bytes),201);await assert.rejects(()=>importOfficial(owner.db,owner.bucket,makePlan(bytes,owner.target,artifact),bytes),/ownership conflict/);pass('prior community ownership is not stolen by operator import');await owner.close();
 const version=await servicesStart('version-conflict'),vp=makePlan(bytes,version.target,artifact);await version.db.prepare('INSERT INTO releases VALUES(?,?,?,?,?,?,?)').bind('drupal','0.1.0','codegraph',JSON.stringify({...vp.listing,name:'existing immutable listing'}),'packages/sha256/'+vp.listing.integrity,vp.listing.integrity,bytes.length).run();await assert.rejects(()=>importOfficial(version.db,version.bucket,vp,bytes),/version conflict/);pass('existing immutable version metadata conflict is not overwritten');await version.close();
 const race=await servicesStart('race'),rp=makePlan(bytes,race.target,artifact);const results=await Promise.all([importOfficial(race.db,race.bucket,rp,bytes),importOfficial(race.db,race.bucket,rp,bytes)]);assert.deepEqual(results.map(r=>r.status).sort(),['imported','unchanged']);pass('concurrent identical official imports converge to one release');await race.close();
 const failure=await servicesStart('failure'),fp=makePlan(bytes,failure.target,artifact);await assert.rejects(()=>importOfficial(failure.db,{put:async()=>{throw Error('R2 failure');}},fp,bytes),/R2 failure/);assert.equal(await failure.db.prepare('SELECT count(*) n FROM extensions').first('n'),0);
 await failure.db.exec("CREATE TRIGGER reject_official AFTER INSERT ON releases BEGIN SELECT RAISE(ABORT,'fixture D1 failure'); END;");await assert.rejects(()=>importOfficial(failure.db,failure.bucket,fp,bytes));assert.equal(await failure.db.prepare('SELECT count(*) n FROM extensions').first('n'),0);assert.equal(await failure.db.prepare('SELECT count(*) n FROM releases').first('n'),0);await failure.db.exec('DROP TRIGGER reject_official');assert.equal((await importOfficial(failure.db,failure.bucket,fp,bytes)).status,'imported');pass('R2 and D1 failures expose no release or orphan owner; exact retry succeeds');await failure.close();
 const key='packages/sha256/'+plan.listing.integrity;await s.bucket.put(key,Buffer.from('tampered'));await assert.rejects(()=>importOfficial(s.db,s.bucket,plan,bytes),/corrupt/);assert.equal(Buffer.from(await(await s.bucket.get(key)).arrayBuffer()).toString(),'tampered');await s.bucket.put(key,bytes);pass('idempotent repeat detects corrupt object and never repairs by silent overwrite');
 await backupRegistry(s.db,s.bucket,path.join(lab,'backup'));const restore=await servicesStart('restore');await restoreRegistry(restore.db,restore.bucket,path.join(lab,'backup'));assert.equal((await importOfficial(restore.db,restore.bucket,{...plan,target:{...restore.target,registryId:s.target.registryId}},bytes)).status,'unchanged');pass('official provenance ownership and bytes survive isolated backup restore');await restore.close();
 const state=s.state;await s.close();const targetFile=path.join(lab,'target.json');fs.writeFileSync(targetFile,await cli(['inspect-local',state]));const planFile=path.join(lab,'plan.json');await cli(['plan',targetFile,artifact,planFile]);await cli(['apply',planFile,'--confirm-plan-sha256','0'.repeat(64)],1);const digest=hash(fs.readFileSync(planFile));assert.equal(JSON.parse(await cli(['apply',planFile,'--confirm-plan-sha256',digest])).status,'unchanged');pass('explicit CLI target plan hash confirmation and repeat operation work');
 // Contract-only transport verification: dummy test credentials, no external requests.
 const seen=[];const transport=async(input,init)=>{const request=input instanceof Request?input:new Request(input,init);seen.push({url:request.url,method:request.method,conditional:request.headers.get('If-None-Match')});if(request.url.endsWith('/settings'))return Response.json({success:true,result:{bindings:[{name:'DB',type:'d1',id:'11111111-1111-1111-1111-111111111111'},{name:'PACKAGES',type:'r2_bucket',bucket_name:'fixture'}]}});if(request.url.includes('api.cloudflare.com'))return Response.json({success:true,result:[{success:true,results:[{value:'registry'}],meta:{changes:1}}]});return new Response(bytes);};
 const remote=remoteBindings({accountId:'a'.repeat(32),databaseId:'11111111-1111-1111-1111-111111111111',bucket:'fixture',workerName:'fixture-worker'},{d1Token:'dummy',r2AccessKeyId:'dummy',r2SecretAccessKey:'dummy'},transport);assert.equal(await remote.db.prepare('SELECT ? value').bind('registry').first('value'),'registry');await remote.bucket.put(key,bytes,{onlyIf:{etagDoesNotMatch:'*'}});assert.deepEqual(Buffer.from(await(await remote.bucket.get(key)).arrayBuffer()),bytes);assert.equal(seen[2].conditional,'*');pass('remote adapter uses fixed account endpoints and conditional S3 creation (contract only)');
 const badRemote=remoteBindings({accountId:'a'.repeat(32),databaseId:'11111111-1111-1111-1111-111111111111',bucket:'wrong-bucket',workerName:'fixture-worker'},{d1Token:'dummy',r2AccessKeyId:'dummy',r2SecretAccessKey:'dummy'},transport);await assert.rejects(()=>badRemote.db.prepare('SELECT 1').first(),/does not match/);pass('remote binding mismatch stops before database or object writes (contract only)');
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({revision:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),dirty:!!execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(),checks,commands,artifactSHA:hash(bytes),artifactBytes:bytes.length,success:true},null,2));
}catch(error){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,commands,error:String(error.stack)},null,2));throw error;}finally{await Promise.allSettled(services.map(s=>s.close()));fs.rmSync(lab,{recursive:true,force:true});}
