import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {createHash,generateKeyPairSync,sign,randomUUID} from 'node:crypto';import {createRequire} from 'node:module';
import {startLocal} from './local.mjs';import {reviewSource} from './review-source.mjs';
const require=createRequire(import.meta.url),{requireSourceReview}=require('../source-review.cjs');
const out=path.resolve(process.env.SOURCE_OUTPUT||'../../.qa/source-budget/policy');fs.mkdirSync(out,{recursive:true});
const lab=fs.mkdtempSync(path.join(os.tmpdir(),'cg-source-policy-')),checks=[],key=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),hash=b=>createHash('sha256').update(b).digest('hex');
const publisherId=hash(key.publicKey.export({format:'der',type:'spki'})),repository='https://github.com/review/example',revision='a'.repeat(40),source='packages/demo.cgext';
const pkg={format:'codegraph-extension-1',package:{name:'source-demo',version:'1.0.0',main:'index.cjs',codegraph:{id:'source-demo',apiVersion:1,capabilities:['frameworks']}},files:{'index.cjs':'module.exports=()=>({frameworks:[]});','vendor/dependency.cjs':'module.exports = 42;'}};
const bytes=Buffer.from(JSON.stringify(pkg)),artifact=path.join(lab,'demo.cgext');fs.writeFileSync(artifact,bytes);
const options={artifact,repository,revision,source,publisherId};
function mock({privateRepo=false,status=200,wrongCommit=false,wrongBytes=false}={}){let n=0;return async(url,opts)=>{assert.equal(opts.redirect,'error');assert.equal(opts.credentials,'omit');assert.ok(!opts.headers.Authorization);n++;assert.ok(url.startsWith(n===3?'https://raw.githubusercontent.com/review/example/':'https://api.github.com/repos/review/example'));return new Response(n===1?JSON.stringify({private:privateRepo,full_name:'review/example',html_url:repository}):n===2?JSON.stringify({sha:wrongCommit?'b'.repeat(40):revision}):wrongBytes?'tampered':bytes,{status:n===1?status:200});};}
function pass(name){checks.push(name);console.log('PASS',name);fs.writeFileSync(path.join(out,'progress.json'),JSON.stringify({checks},null,2));}
let server,normal;
try{
 const review=await reviewSource(options,mock());assert.equal(review.integrity,hash(bytes));pass('bounded public repository commit and entire package byte review (mocked provider contract)');
 for(const overrides of [{privateRepo:true},{status:404},{status:403},{wrongCommit:true},{wrongBytes:true}])await assert.rejects(()=>reviewSource(options,mock(overrides)));pass('private unavailable rate-limited wrong-commit and unrelated package sources rejected');
 for(const override of [{repository:'https://example.com/source'},{repository:'https://github.com/review/example/redirect'},{revision:'main'},{source:'../secret.cgext'},{source:'packages/%2e%2e.cgext'}])await assert.rejects(()=>reviewSource({...options,...override},()=>{throw Error('network must not run');}));pass('source host revision and traversal validated before any fetch');
 const claim={source:repository,sourceRevision:revision,sourcePath:source};
 assert.equal(requireSourceReview([review],pkg.package,hash(bytes),publisherId,claim).verification,'public-committed-package-bytes');
 for(const [p,h,owner,c] of [[pkg.package,'0'.repeat(64),publisherId,claim],[{...pkg.package,version:'2.0.0'},hash(bytes),publisherId,claim],[pkg.package,hash(bytes),'1'.repeat(64),claim],[pkg.package,hash(bytes),publisherId,{...claim,sourceRevision:'b'.repeat(40)}]])assert.throws(()=>requireSourceReview([review],p,h,owner,c));pass('review binds exact id version artifact publisher repository and revision');
 server=await startLocal({state:path.join(lab,'reviewed'),testing:true,sourceReviews:[review]});
 const signed=(override={},signKey=key)=>{const payload=JSON.stringify({name:'Source demo',description:'Reviewed source',publisher:'Test',readme:'Test',...claim,artifact:bytes.toString('base64'),timestamp:Date.now(),nonce:randomUUID(),...override});return {payload,publicKey:signKey.publicKey.export({format:'jwk'}),signature:sign('sha256',Buffer.from(payload),{key:signKey.privateKey,dsaEncoding:'ieee-p1363'}).toString('base64')};};
 let count=0;const post=async(s,body,expected)=>{const r=await fetch('http://127.0.0.1:'+s.port+'/api/publish',{method:'POST',headers:{'CF-Connecting-IP':'192.0.2.'+(++count)},body:JSON.stringify(body)});const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return data;};
 await post(server,signed({source:'https://example.com/placeholder'}),400);await post(server,signed({sourceRevision:'main'}),400);await post(server,signed({sourcePath:'other.cgext'}),400);await post(server,signed({sourceReview:review}),400);pass('real workerd rejects missing mismatched and spoofed source provenance');
 const bad=JSON.parse(bytes);bad.files['index.cjs']+='\n// changed';await post(server,signed({artifact:Buffer.from(JSON.stringify(bad)).toString('base64')}),400);pass('changed artifact cannot reuse reviewed source admission');
 await post(server,{...signed(),signature:'AAAA'},400);await post(server,signed({official:true}),400);pass('signature and official spoof defenses remain active');
 assert.equal((await server.db.prepare('SELECT count(*) n FROM releases').first()).n,0);assert.equal((await server.bucket.list()).objects.length,0);pass('failed source admission writes no owner release nonce or package');
 const listing=await post(server,signed(),201);assert.equal(listing.sourceReview.integrity,hash(bytes));assert.equal(listing.official,false);pass('real workerd publishes trusted source proof from operator policy only');
 await post(server,signed(),400);await post(server,signed({},generateKeyPairSync('ec',{namedCurve:'prime256v1'})),400);assert.deepEqual(Buffer.from(await(await fetch('http://127.0.0.1:'+server.port+'/api/download/source-demo/1.0.0')).arrayBuffer()),bytes);pass('immutable bytes ownership and reviewed listing persist after refused replacements');
 normal=await startLocal({state:path.join(lab,'production'),sourceReviews:[review]});await post(normal,signed(),400);pass('production Worker ignores test binding policies and defaults to empty approved list');
 fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify({success:true,checks,review,scope:'Public provider responses mocked; actual local workerd+D1+R2 admission exercised'},null,2));
}finally{await server?.close();await normal?.close();fs.rmSync(lab,{recursive:true,force:true});}
