/**
 * Bash completion emitter. Produces a `_codegraph` function registered
 * via `complete -F _codegraph codegraph`. Uses `compgen -W` for word
 * lists and `compgen -f` / `-d` for file/dir completion.
 */

import type { Command } from 'commander';
import { describeCommand, type CommandDesc, type OptionDesc } from './introspect';

const allFlagsFor = (opts: OptionDesc[]): string[] => {
  const out: string[] = [];
  for (const o of opts) {
    if (o.short) out.push(o.short);
    if (o.long) out.push(o.long);
  }
  return out;
};

// Options whose previous word means "complete a path", not "complete a flag".
const valueOptionsByHint = (opts: OptionDesc[]) => {
  const file: string[] = [];
  const dir: string[] = [];
  for (const o of opts) {
    if (!o.takesValue) continue;
    const flags = [o.short, o.long].filter(Boolean) as string[];
    if (o.valueHint === 'file') file.push(...flags);
    else if (o.valueHint === 'directory') dir.push(...flags);
  }
  return { file, dir };
};

const subcommandCase = (root: CommandDesc): string => {
  const arms = root.subcommands.map((sub) => {
    const surface = [sub.name, ...sub.aliases].join('|');
    const flags = allFlagsFor(sub.options);
    const { file: fileOpts, dir: dirOpts } = valueOptionsByHint(sub.options);
    // Positional hint: if any arg wants files/dirs, fall back to file
    // completion when the user isn't completing a flag.
    const argHint = sub.args.find((a) => a.hint !== 'none')?.hint ?? 'none';

    const flagList = flags.join(' ');
    const valueHandling: string[] = [];
    if (fileOpts.length > 0) {
      valueHandling.push(`        ${fileOpts.join('|')})`);
      valueHandling.push(`          COMPREPLY=( $(compgen -f -- "$cur") ); return 0 ;;`);
    }
    if (dirOpts.length > 0) {
      valueHandling.push(`        ${dirOpts.join('|')})`);
      valueHandling.push(`          COMPREPLY=( $(compgen -d -- "$cur") ); return 0 ;;`);
    }

    const positionalFallback =
      argHint === 'file'
        ? `\n      if [[ "$cur" != -* ]]; then\n        COMPREPLY=( $(compgen -f -- "$cur") ); return 0\n      fi`
        : argHint === 'directory'
          ? `\n      if [[ "$cur" != -* ]]; then\n        COMPREPLY=( $(compgen -d -- "$cur") ); return 0\n      fi`
          : '';

    return `    ${surface})
      case "$prev" in
${valueHandling.length > 0 ? valueHandling.join('\n') + '\n' : ''}      esac${positionalFallback}
      COMPREPLY=( $(compgen -W "${flagList}" -- "$cur") )
      return 0
      ;;`;
  });

  return arms.join('\n');
};

export const emitBash = (program: Command): string => {
  const root = describeCommand(program);
  const subNames = root.subcommands.flatMap((s) => [s.name, ...s.aliases]).join(' ');
  const rootFlags = allFlagsFor(root.options).join(' ');

  return `# Bash completion for codegraph.
# Generated by \`codegraph completions bash\` — do not edit by hand.
# Install: source this file, or drop it in
#   ~/.local/share/bash-completion/completions/codegraph
# (requires the bash-completion package).

_codegraph() {
  local cur prev words cword
  _init_completion 2>/dev/null || {
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    words=("\${COMP_WORDS[@]}")
    cword=$COMP_CWORD
  }

  # Find the subcommand position (first non-flag token after the script).
  local sub=""
  local i
  for (( i=1; i < cword; i++ )); do
    if [[ "\${words[i]}" != -* ]]; then
      sub="\${words[i]}"
      break
    fi
  done

  if [[ -z "$sub" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "${rootFlags} --help --version" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "${subNames}" -- "$cur") )
    fi
    return 0
  fi

  case "$sub" in
${subcommandCase(root)}
  esac
}

complete -F _codegraph codegraph
`;
};
