/**
 * Fish completion emitter. Each `complete` line registers a single
 * piece of completion metadata; fish stitches them together at
 * tab-time. No script, no functions — just declarations.
 */

import type { Command } from 'commander';
import { describeCommand, type CommandDesc, type OptionDesc } from './introspect';

const fishEscape = (s: string): string => s.replace(/'/g, "\\'");

const subcommandNamesExpr = (root: CommandDesc): string =>
  root.subcommands.flatMap((s) => [s.name, ...s.aliases]).join(' ');

const optionLine = (cmdCondition: string, opt: OptionDesc): string => {
  const parts: string[] = [`complete -c codegraph -n '${cmdCondition}'`];
  if (opt.short) parts.push(`-s ${opt.short.replace(/^-/, '')}`);
  if (opt.long) parts.push(`-l ${opt.long.replace(/^--/, '')}`);
  if (opt.takesValue) {
    parts.push('-r');                    // option requires an argument
    if (opt.valueHint === 'file') parts.push('-F');
    else if (opt.valueHint === 'directory') parts.push('-F'); // fish has no -D; -F + dir hint description
    else parts.push('-x');               // arg required, not a file
  }
  if (opt.description) parts.push(`-d '${fishEscape(opt.description)}'`);
  return parts.join(' ');
};

export const emitFish = (program: Command): string => {
  const root = describeCommand(program);
  const subs = subcommandNamesExpr(root);

  // Root: list subcommands when none chosen yet.
  const lines: string[] = [
    '# Fish completion for codegraph.',
    "# Generated by `codegraph completions fish` — do not edit by hand.",
    '# Install: place in ~/.config/fish/completions/codegraph.fish',
    '',
    "complete -c codegraph -n '__fish_use_subcommand' -f",
  ];

  // Top-level option flags (apply when no subcommand chosen yet).
  for (const opt of root.options) {
    lines.push(optionLine('__fish_use_subcommand', opt));
  }

  // Each subcommand as a candidate at position 1.
  for (const sub of root.subcommands) {
    const desc = fishEscape(sub.description);
    for (const name of [sub.name, ...sub.aliases]) {
      lines.push(
        `complete -c codegraph -n '__fish_use_subcommand' -a '${fishEscape(name)}' -d '${desc}'`,
      );
    }
  }

  lines.push('');

  // Per-subcommand options + positional file completion.
  for (const sub of root.subcommands) {
    const allNames = [sub.name, ...sub.aliases];
    // `__fish_seen_subcommand_from` accepts space-separated names.
    const cond = `__fish_seen_subcommand_from ${allNames.join(' ')}`;
    for (const opt of sub.options) {
      lines.push(optionLine(cond, opt));
    }
    const fileArg = sub.args.find((a) => a.hint === 'file');
    const dirArg = sub.args.find((a) => a.hint === 'directory');
    if (fileArg) {
      lines.push(`complete -c codegraph -n '${cond}' -F`);
    } else if (dirArg) {
      lines.push(`complete -c codegraph -n '${cond}' -a '(__fish_complete_directories)'`);
    }
    lines.push('');
  }

  // Suppress fallthrough file completion when no completion matches —
  // by default fish would offer files for any command, which is noisy
  // for commands that don't take a path.
  void subs;

  return lines.join('\n') + '\n';
};
