/**
 * PowerShell completion emitter. Hand-written, static (no callback
 * into the binary). Follows the clap_complete idiom exactly because
 * it's the most-deployed PS completion pattern (every Rust CLI uses
 * it) and PowerShell's `TabExpansion2` testability makes the static
 * path much friendlier than zsh's.
 *
 * The shape:
 *   Register-ArgumentCompleter -Native -CommandName codegraph -ScriptBlock {
 *     # Walk $commandAst.CommandElements → join non-flag, non-value
 *     # tokens with ';' → "codegraph", "codegraph;init", etc.
 *     # switch on that path string → emit subcommand + option candidates
 *     # filter by $wordToComplete prefix
 *   }
 *
 * Known clap_complete bugs we sidestep:
 *   #5820 — single-quote escaping. PS single-quoted strings escape
 *           a single quote by doubling it. We double-escape descriptions.
 *   #5341 — empty help strings break completions. We default to the
 *           item name when description is empty.
 */

import type { Command } from 'commander';
import { describeCommand, type CommandDesc, type OptionDesc } from './introspect';

// PowerShell single-quoted strings: '' is the only escape needed.
const psEscape = (s: string): string => s.replace(/'/g, "''");

// Empty descriptions break completion rendering; fall back to the
// item itself so the menu always has something to show.
const descOrName = (desc: string, name: string): string =>
  desc.trim().length > 0 ? desc : name;

const optionResult = (opt: OptionDesc): string[] => {
  // Emit one CompletionResult line per surface form. Short and long
  // forms get separate entries so both show up in the menu.
  const desc = psEscape(descOrName(opt.description, opt.long ?? opt.short ?? ''));
  const out: string[] = [];
  for (const flag of [opt.short, opt.long]) {
    if (!flag) continue;
    out.push(
      `            [CompletionResult]::new('${psEscape(flag)}', '${psEscape(flag)}', [CompletionResultType]::ParameterName, '${desc}')`,
    );
  }
  return out;
};

const commandResult = (sub: CommandDesc): string[] => {
  // Subcommand candidate plus all its aliases. Each gets its own
  // CompletionResult so they all appear in the menu.
  const desc = psEscape(descOrName(sub.description, sub.name));
  return [sub.name, ...sub.aliases].map(
    (n) =>
      `            [CompletionResult]::new('${psEscape(n)}', '${psEscape(n)}', [CompletionResultType]::ParameterValue, '${desc}')`,
  );
};

const switchCaseFor = (commandPath: string, cmd: CommandDesc, isRoot: boolean): string => {
  // PS switch case: 'codegraph;init' or 'codegraph'. The body lists
  // valid candidates at that point: subcommands (if any) + options.
  const lines: string[] = [];
  // Subcommands first (only meaningful for the root; per-sub cases
  // don't dispatch deeper because codegraph is flat — no sub-subs).
  for (const sub of cmd.subcommands) {
    lines.push(...commandResult(sub));
  }
  // Options.
  for (const opt of cmd.options) {
    lines.push(...optionResult(opt));
  }
  // At the root, expose --help / --version always.
  if (isRoot) {
    lines.push(
      `            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Show help')`,
      `            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Show version')`,
    );
  }
  return `        '${psEscape(commandPath)}' {
${lines.join('\n')}
            break
        }`;
};

export const emitPowershell = (program: Command): string => {
  const root = describeCommand(program);
  const cmdName = root.name;

  const cases: string[] = [switchCaseFor(cmdName, root, true)];
  for (const sub of root.subcommands) {
    // Cover canonical name + each alias as a separate switch arm so
    // `codegraph a<TAB>` (alias for `affected`) works the same as
    // `codegraph affected<TAB>`.
    for (const surface of [sub.name, ...sub.aliases]) {
      cases.push(switchCaseFor(`${cmdName};${surface}`, sub, false));
    }
  }

  return `using namespace System.Management.Automation
using namespace System.Management.Automation.Language

# PowerShell completion for ${cmdName}.
# Generated by \`${cmdName} completions powershell\` — do not edit by hand.
# Install: dot-source this file from your \$PROFILE, e.g.
#   Add-Content \$PROFILE ". '<path-to-this-file>'"

Register-ArgumentCompleter -Native -CommandName '${psEscape(cmdName)}' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $commandElements = $commandAst.CommandElements
    $command = @(
        '${psEscape(cmdName)}'
        for ($i = 1; $i -lt $commandElements.Count; $i++) {
            $element = $commandElements[$i]
            if ($element -isnot [StringConstantExpressionAst] -or
                $element.StringConstantType -ne [StringConstantType]::BareWord -or
                $element.Value.StartsWith('-') -or
                $element.Value -eq $wordToComplete) { break }
            $element.Value
        }
    ) -join ';'

    $completions = @(switch ($command) {
${cases.join('\n')}
    })

    $completions.Where{ $_.CompletionText -like "$wordToComplete*" } |
        Sort-Object -Property ListItemText
}
`;
};
