/**
 * Zsh completion emitter. Produces an `_codegraph` function suitable
 * for installation on the `fpath`. Uses the `_arguments` / `_values`
 * idiom — the same style sema-lisp and fedit generate.
 */

import type { Command } from 'commander';
import { describeCommand, type CommandDesc, type CompletionHint, type OptionDesc } from './introspect';

// Inside single-quoted zsh strings we only need to handle `'` and the
// `[…]` description delimiters of `_arguments`. Keeping the escape set
// minimal avoids surprising users who read the script.
const zshEscape = (s: string): string =>
  s.replace(/'/g, "'\\''").replace(/\[/g, '\\[').replace(/\]/g, '\\]');

const actionFor = (hint: CompletionHint): string => {
  switch (hint) {
    case 'file':
      return '_files';
    case 'directory':
      return '_files -/';
    case 'none':
      return '';
  }
};

const optionSpec = (opt: OptionDesc): string => {
  // `_arguments` spec format:
  //   '(-x --xx)'{-x,--xx}'[description]:value name:action'
  // For boolean flags (no value): '--flag[description]'
  // For both short + long: paired exclusion + brace expansion.
  const desc = zshEscape(opt.description);
  const valuePart = opt.takesValue
    ? `:${zshEscape(opt.valueName ?? 'value')}:${actionFor(opt.valueHint)}`
    : '';

  if (opt.short && opt.long) {
    return `'(${opt.short} ${opt.long})'{${opt.short},${opt.long}}'[${desc}]${valuePart}'`;
  }
  const flag = opt.long ?? opt.short!;
  return `'${flag}[${desc}]${valuePart}'`;
};

const argSpec = (idx: number, arg: { name: string; required: boolean; variadic: boolean; hint: CompletionHint }): string => {
  const action = actionFor(arg.hint) || '( )';
  if (arg.variadic) {
    return `'*:${zshEscape(arg.name)}:${action}'`;
  }
  const prefix = arg.required ? `${idx + 1}` : `:${idx + 1}`;
  return `'${prefix}:${zshEscape(arg.name)}:${action}'`;
};

const subcommandDispatchFn = (root: CommandDesc): string => {
  // Per-subcommand argument spec functions, named `_codegraph_<sub>`.
  const perSub = root.subcommands.map((sub) => {
    const argLines = sub.args.map((a, i) => `    ${argSpec(i, a)}`);
    const optLines = sub.options.map((o) => `    ${optionSpec(o)}`);
    const lines = [...optLines, ...argLines];
    const body = lines.length > 0 ? `\n  _arguments -s -S \\\n${lines.join(' \\\n')}\n` : '\n  return 0\n';
    return `_codegraph_${sub.name}() {${body}}`;
  });

  // The values list passed to `_values` — `subname[description]` per
  // canonical name. Aliases get their own line so they show up in tab
  // listings.
  const valueLines = root.subcommands.flatMap((sub) => {
    const desc = zshEscape(sub.description);
    return [sub.name, ...sub.aliases].map((n) => `      '${zshEscape(n)}[${desc}]'`);
  });

  // Case dispatch from canonical name OR alias to the per-sub function.
  const caseArms = root.subcommands
    .map((sub) => {
      const pattern = [sub.name, ...sub.aliases].map(zshEscape).join('|');
      return `      ${pattern}) _codegraph_${sub.name} ;;`;
    })
    .join('\n');

  return `${perSub.join('\n\n')}

_codegraph_commands() {
  local -a _commands
  _values 'codegraph command' \\
${valueLines.join(' \\\n')}
}

_codegraph_dispatch() {
  case $words[1] in
${caseArms}
  esac
}`;
};

export const emitZsh = (program: Command): string => {
  const root = describeCommand(program);
  const rootOptions = root.options.map((o) => `    ${optionSpec(o)}`).join(' \\\n');

  return `#compdef codegraph
# Zsh completion for codegraph.
# Generated by \`codegraph completions zsh\` — do not edit by hand.
# Install: place on your \$fpath (e.g. ~/.zsh/completions/_codegraph),
# then \`autoload -Uz compinit && compinit\`.

${subcommandDispatchFn(root)}

_codegraph() {
  local context state state_descr line
  typeset -A opt_args

  _arguments -C \\
${rootOptions} \\
    '1: :_codegraph_commands' \\
    '*::arg:->args'

  case $state in
    args) _codegraph_dispatch ;;
  esac
}

_codegraph "$@"
`;
};
