// Reproduce the shipped subset with npm ci --ignore-scripts, then npm run build.
// No runtime package/CDN is used. --check compares every generated byte.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=__dirname,out=path.resolve(root,'../public'),check=process.argv.includes('--check');
const icons=['arrow-up-right','arrow-right','arrow-left','search','download','upload','badge-check','plug','refresh-cw','shield-check','code-xml','file-code-2','files','copy','x','chevron-left','chevron-right','circle-alert','loader-circle','trash-2','power','key-round','external-link','package','monitor','circle-check'];
const artifacts=new Map(),inputs={};
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function input(rel){const b=fs.readFileSync(path.join(root,'node_modules',rel));inputs[rel]=hash(b);return b;}
const packages={};for(const name of ['lucide-static','@fontsource-variable/archivo','@fontsource/ibm-plex-mono'])packages[name]=JSON.parse(input(name+'/package.json')).version;
assert.equal(packages['lucide-static'],'0.468.0');assert.equal(packages['@fontsource-variable/archivo'],'5.2.8');assert.equal(packages['@fontsource/ibm-plex-mono'],'5.2.7');
const svg={};for(const name of icons){const s=input('lucide-static/icons/'+name+'.svg').toString();svg[name]=s.slice(s.indexOf('>\n',s.indexOf('<svg'))+2,s.lastIndexOf('</svg>')).trim();assert.ok(svg[name].startsWith('<'));}
artifacts.set('icons.js',Buffer.from(`// Generated Lucide ${packages['lucide-static']} subset. See /licenses/lucide.txt and /licenses/feather.txt.\n'use strict';\nconst lucidePaths=Object.freeze(${JSON.stringify(svg)});\nfunction uiIcon(name){if(!Object.hasOwn(lucidePaths,name))throw Error('Unknown bundled icon');return '<svg class="ui-icon" data-lucide="'+name+'" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">'+lucidePaths[name]+'</svg>';}\nfunction paintIcons(root=document){root.querySelectorAll('i[data-ui]').forEach(el=>{el.outerHTML=uiIcon(el.dataset.ui);});}\npaintIcons();\n`));
artifacts.set('licenses/lucide.txt',input('lucide-static/LICENSE'));
artifacts.set('licenses/archivo.txt',input('@fontsource-variable/archivo/LICENSE'));
artifacts.set('licenses/ibm-plex-mono.txt',input('@fontsource/ibm-plex-mono/LICENSE'));
const fonts=[['@fontsource-variable/archivo','archivo-latin-wght-normal.woff2'],['@fontsource/ibm-plex-mono','ibm-plex-mono-latin-400-normal.woff2'],['@fontsource/ibm-plex-mono','ibm-plex-mono-latin-500-normal.woff2'],['@fontsource/ibm-plex-mono','ibm-plex-mono-latin-600-normal.woff2']];
for(const [pkg,file] of fonts)artifacts.set('fonts/'+file,input(pkg+'/files/'+file));
const css=`/* Local Latin subsets; other glyphs use system fallbacks. OFL notices in /licenses/. */\n@font-face{font-family:'Archivo Variable';font-style:normal;font-weight:100 900;font-display:swap;src:url('/fonts/archivo-latin-wght-normal.woff2') format('woff2')}\n`+[400,500,600].map(w=>`@font-face{font-family:'IBM Plex Mono';font-style:normal;font-weight:${w};font-display:swap;src:url('/fonts/ibm-plex-mono-latin-${w}-normal.woff2') format('woff2')}`).join('\n')+'\n';
artifacts.set('fonts.css',Buffer.from(css));
const manifest={packages,icons,inputs,outputs:Object.fromEntries([...artifacts].map(([name,b])=>[name,{sha256:hash(b),bytes:b.length}]))};
artifacts.set('asset-manifest.json',Buffer.from(JSON.stringify(manifest,null,2)+'\n'));
for(const [name,b] of artifacts){const p=path.join(out,name);if(check)assert.deepEqual(fs.readFileSync(p),b,name);else{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,b);}}
console.log(JSON.stringify({check,packages,icons:icons.length,files:artifacts.size,bytes:[...artifacts.values()].reduce((n,b)=>n+b.length,0)}));
